# Generated by Django 5.1.1 on 2024-10-22 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='profile_images/'),
        ),
    ]
