# Generated by Django 5.1.1 on 2024-10-23 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_chat'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Chat',
            new_name='ChatMessage',
        ),
        migrations.RenameField(
            model_name='chatmessage',
            old_name='receiver',
            new_name='recipient',
        ),
    ]
