# Generated by Django 5.1.1 on 2024-11-02 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0026_category_remove_userpreference_preferred_categories_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shortspost',
            name='content',
            field=models.CharField(default='Default content', max_length=150),
        ),
    ]
