# Generated by Django 5.1.1 on 2024-11-02 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0027_shortspost_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shortspost',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
