# Generated by Django 5.1.1 on 2024-11-02 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0028_alter_shortspost_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shortspost',
            name='content',
            field=models.CharField(default='Default content', max_length=150),
        ),
    ]
