# Generated by Django 5.1.1 on 2024-11-02 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0030_chatmessage_seen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatmessage',
            name='seen',
        ),
    ]
