# Generated by Django 5.1.1 on 2024-11-02 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0031_remove_chatmessage_seen'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='seen',
            field=models.BooleanField(default=False),
        ),
    ]
