# Generated by Django 5.1.1 on 2024-11-02 18:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0032_chatmessage_seen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videopost',
            name='category',
        ),
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounts.category'),
        ),
        migrations.DeleteModel(
            name='UserPreference',
        ),
    ]
