# Generated by Django 5.1.1 on 2024-11-02 19:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0033_remove_videopost_category_post_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shortspost',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounts.category'),
        ),
    ]
