# Generated by Django 5.1.1 on 2024-11-03 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0035_announcement'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='announcement_images/'),
        ),
        migrations.AddField(
            model_name='announcement',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='announcement_videos/'),
        ),
    ]
