# Generated by Django 5.1.1 on 2024-11-03 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0036_announcement_image_announcement_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
