# Generated by Django 5.1.1 on 2024-11-03 14:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0037_announcement_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='phone_number',
            field=models.CharField(max_length=15, validators=[django.core.validators.RegexValidator('^\\d{10,15}$', 'Enter a valid phone number with 10-15 digits')]),
        ),
    ]
