# Generated by Django 5.1.1 on 2024-11-04 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0042_post_likes_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shortspost',
            name='content',
            field=models.CharField(default='I m post shorts', max_length=150),
        ),
    ]
