# Generated by Django 5.1.1 on 2024-11-04 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0045_textpost_likes_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='textpost',
            name='likes_count',
        ),
    ]
