# Generated by Django 5.1.1 on 2024-11-06 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0053_customuser_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='status',
            field=models.CharField(choices=[('O', 'Open'), ('C', 'Close')], max_length=1),
        ),
    ]
