# Generated by Django 5.1.1 on 2024-11-07 15:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0058_remove_post_likes_alter_post_likes_count_post_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='likes',
        ),
        migrations.AddField(
            model_name='post',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_image_posts', to=settings.AUTH_USER_MODEL),
        ),
    ]
