# Generated by Django 5.1.1 on 2024-11-07 15:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0059_remove_post_likes_post_likes'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment2',
            name='post',
        ),
        migrations.AddField(
            model_name='comment2',
            name='content_type',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='comment2',
            name='object_id',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
