# Generated by Django 5.1.1 on 2024-11-07 17:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0061_comment3'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment2',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='comment2',
            name='object_id',
        ),
        migrations.RemoveField(
            model_name='comment3',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='comment3',
            name='object_id',
        ),
        migrations.AddField(
            model_name='comment2',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments_for_comment', to='accounts.textpost'),
        ),
        migrations.AddField(
            model_name='comment3',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments_for_comment3', to='accounts.imagepost'),
        ),
    ]
