# Generated by Django 5.1.1 on 2024-11-07 17:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0062_remove_comment2_content_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment2',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='accounts.textpost'),
        ),
        migrations.AlterField(
            model_name='comment3',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments3', to='accounts.imagepost'),
        ),
    ]
