# Generated by Django 5.1.1 on 2024-11-07 18:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0064_comment4'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment4',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments4', to='accounts.videopost'),
        ),
    ]
