# Generated by Django 5.1.1 on 2024-11-07 21:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0066_comment5'),
    ]

    operations = [
        migrations.AddField(
            model_name='shortspost',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_shorts_posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='shortspost',
            name='likes_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
