# Generated by Django 5.1.1 on 2024-11-07 21:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0067_shortspost_likes_shortspost_likes_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment5',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments5', to='accounts.shortspost'),
        ),
        migrations.AlterField(
            model_name='shortspost',
            name='content',
            field=models.TextField(),
        ),
    ]
